### PR TITLE
Update TT-NN to 0.53.0-rc48

### PR DESCRIPTION
**Pull request by ayerofieiev-tt**
This PR updates TT-NN wheel to the latest pre-release version.

### CODE REVIEW

**Comment by jerrysky3** [comment]
The conv2d PR #414 will need this version bump to be merged first; otherwise many conv2d failed on rc47 with the error:
```
Failed to run. Raised exception: TT_FATAL @ /tmp/build-via-sdist-2jj25avz/metal_libs-0.53.0rc47+wormhole.b0/ttnn/cpp/ttnn/tensor/layout/tensor_layout.cpp:131: shard_spec.shape[0] % alignment_[-2] == 0 and shard_spec.shape[1] % alignment_[-1] == 0
info:
In shard mode ShardMode::PHYSICAL, physical shard shape {100, 32} is not compatible with alignment Alignment([32, 32])!
backtrace:
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x8b687b) [0x7fb41cdfc87b]
 --- tt::tt_metal::TensorLayout::compute_shard_spec_buffer(tt::tt_metal::SimpleShape const&) const
 --- tt::tt_metal::tensor_impl::allocate_buffer_on_device(tt::tt_metal::v0::Device*, tt::tt_metal::SimpleShape const&, tt::tt_metal::TensorLayout const&)
 --- tt::tt_metal::create_device_tensor(tt::tt_metal::SimpleShape const&, tt::tt_metal::TensorLayout const&, tt::tt_metal::v0::Device*)
 --- tt::tt_metal::create_device_tensor(ttnn::types::Shape const&, tt::tt_metal::DataType, tt::tt_metal::Layout, tt::tt_metal::v0::Device*, tt::tt_metal::MemoryConfig const&, std::__1::optional<tt::tt_metal::Tile> const&)
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(_ZN2tt8tt_metal9operation29generic_create_output_tensorsIN4ttnn10operations13data_movement35InterleavedToShardedDeviceOperationEEENS1_21program_output_helperIT_Xsr18has_create_programIS8_EE5valueEE4typeERKS8_RKNSt3__16vectorINS0_6TensorENSD_9allocatorISF_EEEENSD_8optionalINS0_8DataTypeEEENS0_6LayoutERKNSL_INS0_12MemoryConfigEEERKNSL_INS0_4TileEEE+0x2b9) [0x7fb41d7b1089]
 --- ttnn::operations::data_movement::InterleavedToShardedDeviceOperation::create_output_tensors(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&) const
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x9170f9) [0x7fb41ce5d0f9]
 --- tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_return_value_t ttnn::device_operation::detail::launch_on_single_device<tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>>(unsigned char, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::operation_attributes_t const&, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_args_t const&)
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x1db0e9a) [0x7fb41e2f6e9a]
 --- tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_return_value_t ttnn::device_operation::detail::invoke<tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>>(unsigned char, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::operation_attributes_t const&, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_args_t const&)
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x1db020b) [0x7fb41e2f620b]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x1dad04b) [0x7fb41e2f304b]
 --- std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> tt::tt_metal::operation::run<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>(tt::tt_metal::operation::DeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>&&, std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor const>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor const>>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor>>> const&, unsigned char)
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x9155e7) [0x7fb41ce5b5e7]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x910367) [0x7fb41ce56367]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x130bd54) [0x7fb41d851d54]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x130cb3c) [0x7fb41d852b3c]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x130d0fb) [0x7fb41d8530fb]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x130b209) [0x7fb41d851209]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x1309fb3) [0x7fb41d84ffb3]
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x13084b9) [0x7fb41d84e4b9]
 --- std::__1::tuple<tt::tt_metal::Tensor, ttnn::operations::sliding_window::ParallelConfig, ttnn::operations::sliding_window::ParallelConfig, bool, bool> ttnn::operations::conv::conv2d::shard_or_reshard_tensor_if_required<tt::tt_metal::v0::Device>(tt::tt_metal::v0::Device*, tt::tt_metal::Tensor const&, ttnn::operations::conv::conv2d::Conv2dConfig const&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool)
 --- std::__1::tuple<tt::tt_metal::Tensor, unsigned int, unsigned int, tt::tt_metal::Tensor, std::__1::optional<tt::tt_metal::Tensor>> ttnn::operations::conv::conv2d::conv2d<tt::tt_metal::v0::Device>(tt::tt_metal::Tensor const&, tt::tt_metal::Tensor const&, tt::tt_metal::v0::Device*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, std::__1::array<unsigned int, 2ul>, std::__1::array<unsigned int, 2ul>, std::__1::array<unsigned int, 2ul>, std::__1::array<unsigned int, 2ul>, unsigned int, std::__1::optional<tt::tt_metal::Tensor const>, std::__1::optional<ttnn::operations::conv::conv2d::Conv2dConfig const>, std::__1::optional<tt::tt_metal::MemoryConfig const>)
 --- ttnn::operations::conv::conv2d::Conv2dOperation::invoke(unsigned char, tt::tt_metal::Tensor const&, tt::tt_metal::Tensor const&, tt::tt_metal::v0::Device*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, std::__1::array<unsigned int, 2ul>, std::__1::array<unsigned int, 2ul>, std::__1::array<unsigned int, 2ul>, std::__1::array<unsigned int, 2ul>, unsigned int, std::__1::optional<tt::tt_metal::Tensor const>, std::__1::optional<ttnn::operations::conv::conv2d::Conv2dConfig const>, std::__1::optional<tt::tt_metal::MemoryConfig const>)
 --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x7b101f) [0x7fb41ccf701f]
```

**Comment by jerrysky3** [comment]
This version fails two tests:
- `tests/models/torchvision/test_torchvision_image_classification.py::test_torchvision_image_classification[model_info_and_mode46]`
- tests/models/torchvision/test_torchvision_image_classification.py::test_torchvision_image_classification[model_info_and_mode47]`

Here is the error:
```
>       ttnn_matmul_13 = ttnn_decorators_ttnn_matmul(ttnn_to_device_44, ttnn_permute_25);  ttnn_to_device_44 = ttnn_permute_25 = None

<eval_with_key>.14:504:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = FastOperation(python_fully_qualified_name='ttnn.matmul', function=<ttnn._ttnn.operations.matmul.matmul_t object at 0x7...<function default_postprocess_golden_function_outputs at 0x7f70d9c59c10>, is_cpp_operation=True, is_experimental=False)
function_args = (ttnn.Tensor(<buffer is not allocated>, shape=Shape([784[800], 192]), dtype=DataType::BFLOAT16, layout=Layout::TILE), ttnn.Tensor(<buffer is not allocated>, shape=Shape([192, 576]), dtype=DataType::BFLOAT16, layout=Layout::TILE))
function_kwargs = {}

    def __call__(self, *function_args, **function_kwargs):
>       return self.function(*function_args, **function_kwargs)
E       RuntimeError: TT_FATAL @ /tmp/build-via-sdist-eym01d3s/metal_libs-0.53.0rc48+wormhole.b0/ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:1252: program_config.out_block_h % program_config.out_subblock_h == 0
E       info:
E       Error: incompatible values 1 and 3
E       backtrace:
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x8c7649) [0x7f70db5ec649]
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x13b5202) [0x7f70dc0da202]
E        --- ttnn::operations::matmul::Matmul::validate(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor const>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor const>>> const&) const
E        --- void ttnn::device_operation::detail::launch_on_worker_thread<tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>, unsigned char, long, tt::tt_metal::operation::DeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_args_t, std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>, tt::tt_metal::v0::Device*>(unsigned char, long, tt::tt_metal::operation::DeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>> const&, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_args_t const&, std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>&, tt::tt_metal::v0::Device*&)
E        --- tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_return_value_t ttnn::device_operation::detail::launch_on_single_device<tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>>(unsigned char, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::operation_attributes_t const&, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_args_t const&)
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x1d7cb7a) [0x7f70dcaa1b7a]
E        --- tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_return_value_t ttnn::device_operation::detail::invoke<tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>>(unsigned char, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::operation_attributes_t const&, tt::tt_metal::operation::OldInfraDeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>::tensor_args_t const&)
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x1d7beeb) [0x7f70dcaa0eeb]
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x1d78d2b) [0x7f70dca9dd2b]
E        --- std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> tt::tt_metal::operation::run<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>(tt::tt_metal::operation::DeviceOperation<std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>>>&&, std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor const>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor const>>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor>>> const&, unsigned char)
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x13c1581) [0x7f70dc0e6581]
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(+0x13c22a5) [0x7f70dc0e72a5]
E        --- ttnn::operations::matmul::matmul(tt::tt_metal::Tensor const&, tt::tt_metal::Tensor const&, std::__1::optional<tt::tt_metal::Tensor const>, ttnn::operations::matmul::Matmul const&, unsigned char)
E        --- ttnn::operations::matmul::bound_matmul(tt::tt_metal::Tensor const&, tt::tt_metal::Tensor const&, std::__1::optional<tt::tt_metal::Tensor const> const&, ttnn::operations::matmul::Matmul const&, unsigned char const&)
E        --- /home/jerry/pytorch2.0_ttnn/venv/lib/python3.8/site-packages/ttnn/_ttnn.cpython-38-x86_64-linux-gnu.so(_ZN4ttnn10operations6matmul15MatmulOperation6invokeERKN2tt8tt_metal6TensorES7_bbNSt3__18optionalIKNS4_12MemoryConfigEEENS9_IKNS4_8DataTypeEEENS9_IKNS8_7variantIJNS1_28MatmulMultiCoreProgramConfigENS1_45MatmulMultiCoreNonOptimizedReuseProgramConfigENS1_33MatmulMultiCoreReuseProgramConfigENS1_42MatmulMultiCoreReuseMultiCastProgramConfigENS1_44MatmulMultiCoreReuseMultiCast1DProgramConfigENS1_53MatmulMultiCoreReuseMultiCastDRAMShardedProgramConfigEEEEEERKNS9_IKNS8_12basic_stringIcNS8_11char_traitsIcEENS8_9allocatorIcEEEEEENS9_IKNSG_IJNS_28GrayskullComputeKernelConfigENS_27WormholeComputeKernelConfigEEEEEENS9_IKNS_5types8CoreGridEEERKNS9_IKNS4_4TileEEE+0x2f7) [0x7f70dc057eb7]
```

**Comment by jerrysky3** [comment]
It looks like the error is only reproducible on N150. Is the CI runner N150? https://github.com/tenstorrent/tt-metal/issues/15360

**Comment by ayerofieiev-tt** [comment]
@jerrysky3 CI runners are not uniform and have a couple N150 and a couple N300

**Comment by ayerofieiev-tt** [comment]
I expect this issue is solved now in the latest wheel
https://github.com/tenstorrent/pytorch2.0_ttnn/pull/488#issuecomment-2493063775

**Comment by ayerofieiev-tt** [comment]
Closing this for the sake of newer wheels. Though still blocked by issues.

**Pull request closed without merging**
