### PR TITLE
Rework lowering of aten.rsub to use ttnn.neg and ttnn.add

### LINKED ISSUE #484: aten.rsub.Scalar

### PR DESCRIPTION
**Pull request by kevinwuTT**
### Ticket
- Resolves #484 

### Problem description
For lowering `aten.rsub(tensor, scalar)` is equivalent to: `ttnn.sub(scalar, tensor)`

`ttnn.sub` does not support scalar as the first argument, so previously the lowering uses a combination of `ttnn.full` and `ttnn.sub` to get the same effect. However, `ttnn.full` may have some compatibility issues that require changing the layout. 

### What's changed
There does exist a `ttnn.rsub` that supports `(tensor, scalar)` only. It does not support `(tensor, tensor)`, but we can use `ttnn.sub` for that still.

~~Instead, a simpler approach would be to use `ttnn.neg` and `ttnn.add`:~~

~~`ttnn.add(ttnn.negate(tensor), scalar))`~~

### Related:
This improves the handling of extra `layout` ops for this PR: https://github.com/tenstorrent/pytorch2.0_ttnn/pull/322

### TODO:
- [x] File ticket for `ttnn.rsub` support `(tensor, tensor)` like `aten.rsub.Tensor` https://github.com/tenstorrent/tt-metal/issues/15473

### CODE REVIEW

**Comment by jdh8** [comment]
Test are running at https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/12038691438

**Comment by kevinwuTT** [comment]
There does exist a `ttnn.rsub`. So `aten.rsub.Scalar` can be simplified even further. Will run the tests and check if this conflicts with any models.

**Review by ayerofieiev-tt — APPROVED** [review]

**Comment by ayerofieiev-tt** [comment]
CI passed

**Comment by ayerofieiev-tt** [comment]
@jerrysky3 lets temporarily lower pcc and fire a ticket for the team to investigate.

**Pull request merged**
