### PR TITLE
Fix compiling tensor–scalar comparison ops, such as `ttnn.eq`

### PR DESCRIPTION
**Pull request by jdh8**
### Ticket
None

### Problem description
The kernel can now handle tensor–scalar comparison.  We should remove the workaround and make the conversion simple.

### What's changed
For all comparison ops, `ttnn.{eq,ne,lt,le,gt,ge}`, taking a tensor and a scalar

- We no longer need the intermediate `ttnn.full` that broadcasts the scalar to a tensor.
- The tensor shape is no longer required to be a multiple of tiles

This PR should unblock converting several input variations of tensor–scalar comparison.

### CODE REVIEW

**Review by ayerofieiev-tt — APPROVED** [review]

**Comment by jdh8** [comment]
I'm removing `test_if.py`.  We cannot really write an atomic test for `if`.  Model tests provide enough coverage in my opinion.

> (Quote from 5182a9471f6ca649180bf319d23997dcc4dfeaac)
> - The test is highly dependent on other ops.
> - There is no known input variation of control flow yet.
>
> In general, this test is more trouble than it's worth.

**Comment by jdh8** [comment]
This error also occurs when merging other PRs.
```
/home/ubuntu/actions-runner/_work/_tool/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/config/__init__.py:329: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ModuleNotFoundError: No module named 'cv2' (from /home/ubuntu/actions-runner/_work/pytorch2.0_ttnn/pytorch2.0_ttnn/tests/conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest '/home/ubuntu/actions-runner/_work/pytorch2.0_ttnn/pytorch2.0_ttnn/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from tests.utils import calculate_accuracy
../../_tool/Python/3.8.18/x64/lib/python3.8/site-packages/tests/__init__.py:3: in <module>
    from ultralytics.utils import ASSETS, ROOT, WEIGHTS_DIR, checks, is_dir_writeable
../../_tool/Python/3.8.18/x64/lib/python3.8/site-packages/ultralytics/__init__.py:11: in <module>
    from ultralytics.data.explorer.explorer import Explorer
../../_tool/Python/3.8.18/x64/lib/python3.8/site-packages/ultralytics/data/__init__.py:3: in <module>
    from .base import BaseDataset
../../_tool/Python/3.8.18/x64/lib/python3.8/site-packages/ultralytics/data/base.py:12: in <module>
    import cv2
E   ModuleNotFoundError: No module named 'cv2'
```

**Comment by jerrysky3** [comment]
> I'm removing `test_if.py`. We cannot really write an atomic test for `if`. Model tests provide enough coverage in my opinion.
> 
> > (Quote from [5182a94](https://github.com/tenstorrent/pytorch2.0_ttnn/commit/5182a9471f6ca649180bf319d23997dcc4dfeaac))
> > 
> > * The test is highly dependent on other ops.
> > * There is no known input variation of control flow yet.
> > 
> > In general, this test is more trouble than it's worth.

I think we might know why test_if is failing. It is because the `torch.sum` wrongly returns 0 for now, which is used in this test for the condition. @pschang-phy and I are looking into the problem of `torch.sum`

**Comment by jdh8** [comment]
@jerrysky3 and @pschang-phy, I marked `test_sum` xfail at 3f5ec095858d5e0d06b259e9fc68eff74123602d so that we can work in parallel.

**Pull request merged**
