### PR TITLE
Try lowering `aten.mean.default`

### PR DESCRIPTION
**Pull request by jdh8**
### Ticket
tenstorrent/tt-metal#12170

### Problem description
Lower `aten.mean.default` to `ttnn.mean`

### What's changed
Partial lowering of `aten.mean.default`.  This PR contains *N* `ttnn.squeeze` ops to properly squeeze the output for *N*-D tensors.  This is suboptimal and raises a signal for now.  To support `aten.mean.default` properly, we need any of the following:

- Support `keepdim=False` for `ttnn.mean`
- Support tuple `dim` for `ttnn.squeeze`

### CODE REVIEW

**Comment by ayerofieiev-tt** [comment]
@jdh8 there are several PRs from you which are not properly formatted. Please make sure post-commit is installed and run.

**Comment by ayerofieiev-tt** [comment]
I mean these 2
Screenshot 2024-09-04 at 7 50 39 AM

**Comment by ayerofieiev-tt** [comment]
@jdh8 , why don't you use `ttnn.mean`?

https://github.com/search?q=repo%3Atenstorrent%2Ftt-metal%20ttnn.mean&type=code

**Review by ayerofieiev-tt — APPROVED** [review]

**Comment by ayerofieiev-tt** [comment]
Running tests here
https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/10786359878

**Comment by jdh8** [comment]
I'm closing this PR to lower its priority.  This op is not in [the table of input variations](https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/docs/cumulative_input_variations.md) while `aten.mean.dim` is already converted.  A good time to reopen this PR would be when either of the following happens:

- `ttnn.mean` supports `keepdim=False`
- `ttnn.squeeze` supports `dim` tuple

**Pull request closed without merging**
