### PR TITLE
Try converting `floor`

### PR DESCRIPTION
**Pull request by jdh8**
### Ticket
None

### Problem description
Convert `aten.floor` to `ttnn.floor`

### What's changed
The conversion results in an error for now.  I'm not sure how to fix this issue.
```
self = FastOperation(python_fully_qualified_name='ttnn.floor', function=<ttnn._ttnn.operations.unary.floor_t object at 0x7f5f...<function default_postprocess_golden_function_outputs at 0x7f5f7072ec10>, is_cpp_operation=True, is_experimental=False)
function_args = (tensor([[-2.1875,  7.1250, -1.5000,  0.9375],
        [ 6.5000, -2.8125, -7.3438, -5.3125],
        [ 3.4375,  5.6875,  5.0000,  3.4375],
        [-1.5000, -3.7500,  1.8750, -9.7500]], dtype=torch.bfloat16),)
function_kwargs = {}

    def __call__(self, *function_args, **function_kwargs):
>       return self.function(*function_args, **function_kwargs)
E       TypeError: __call__(): incompatible function arguments. The following argument types are supported:
E           1. (self: ttnn._ttnn.operations.unary.floor_t, input_tensor: ttnn._ttnn.deprecated.tensor.Tensor, *, memory_config: Optional[ttnn._ttnn.deprecated.tensor.MemoryConfig] = None, output_tensor: Optional[ttnn._ttnn.deprecated.tensor.Tensor] = None, queue_id: int = 0) -> ttnn._ttnn.deprecated.tensor.Tensor
E       
E       Invoked with: <ttnn._ttnn.operations.unary.floor_t object at 0x7f5f70c19f30>, tensor([[-2.1875,  7.1250, -1.5000,  0.9375],
E               [ 6.5000, -2.8125, -7.3438, -5.3125],
E               [ 3.4375,  5.6875,  5.0000,  3.4375],
E               [-1.5000, -3.7500,  1.8750, -9.7500]], dtype=torch.bfloat16)

../tt-metal/ttnn/ttnn/decorators.py:324: TypeError
```

This error does not happen for existing elementwise unary ops, so I doubt if simple remapping works.  Is there something to do with the type of the tensor?

### CODE REVIEW

**Comment by ayerofieiev-tt** [comment]
You are passing Torch tensor to a TT-NN operation, thats why you get this error.
from_torch, to_torch should be added around

**Comment by ayerofieiev-tt** [comment]
See 
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/torch_ttnn/passes/lowering/add_data_move_pass.py

**Comment by jdh8** [comment]
o7!  I guess the only thing that stops us now is that Grayskull does not support `floor` and maybe other rounding ops. :skull:
```
E       RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_op.cpp:379: arch != tt::ARCH::GRAYSKULL
E       info:
E       Operation is not supported on Grayskull
E       backtrace:
E        --- /home/ubuntu/jdh8/tt-metal/ttnn/ttnn/_ttnn.so(+0x1bcac8) [0x7fa4886a4ac8]
E        --- ttnn::operations::unary::Unary::validate_with_output_tensors(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor>>> const&) const
E        --- /home/ubuntu/jdh8/tt-metal/build/lib/libtt_eager.so(+0x4e55cc) [0x7fa4898655cc]
E        --- /home/ubuntu/jdh8/tt-metal/build/lib/libtt_eager.so(+0x4e553f) [0x7fa48986553f]
```

**Comment by kevinwuTT** [comment]
Can we get the arch during lowering and add fallbacks when GRAYSKULL is detected for these kinds of ops?

**Review by ayerofieiev-tt — APPROVED** [review]

**Pull request merged**
