### PR TITLE
Add test cases for conversion from `aten.lt.Scalar` to `ttnn.lt`

### LINKED ISSUE #591: aten.lt.Scalar

### PR DESCRIPTION
**Pull request by jdh8**
### Ticket
- Resolves #591

### Problem description
Not sure which cases to work on.  Is there a list of failing cases?

### What's changed
- Test cases listed in [`docs/operations/aten.lt.Scalar.md`](https://github.com/tenstorrent/pytorch2.0_ttnn/tree/main/docs/operations/aten.lt.Scalar.md)

### CODE REVIEW

**Comment by ayerofieiev-tt** [comment]
This does not fix the conversion, only expands the test, right? Should PR description be updated or is this still work in progress?

**Comment by swimdi** [comment]
`aten.lt.Scalar` appeared in these model before
```
FLAN-T5
t5-base
t5-large
t5-small
```
but the latest status says it is not remained

**Comment by jdh8** [comment]
@ayerofieiev-tt, I was unsure about if there were more cases to convert.  Now it's crystal clear, and I update the title to reflect that.

**Review by ayerofieiev-tt — APPROVED** [review]

**Comment by jdh8** [comment]
It seems like an I/O issue.  I am trying again.
```
=========================== short test summary info ============================
FAILED tests/models/albert/test_albert_masked_lm.py::test_albert_masked_lm[albert/albert-large-v2-eval] - requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='cdn-lfs.hf.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 7f42431b-fb8f-4f94-a20c-b4e5fc5b3ed8)')
===== 1 failed, 3 passed, 156 deselected, 5 warnings in 156.58s (0:02:36) ======
|                  path                  |     passed     |    failed    | subtotal |
| -------------------------------------- | -------------- | ------------ | -------: |
| models/MobileNetV2/test_MobileNetV2.py | :green_circle: |              |        1 |
| models/albert/test_albert_masked_lm.py | :green_circle: | :red_circle: |        3 |
| TOTAL                                  |              3 |            1 |        4 |
                 Device | INFO     | Closing user mode device drivers
Failure: Tests failed with exit code 1.
```

**Pull request merged**
