### PR TITLE
Model Hand Landmark, with Git LFS.

### PR DESCRIPTION
**Pull request by cthsieh**
### Ticket
None.

### Problem description
This is a revision for PR #140. The binary files are now committed by Git LFS, considering that they are binary and we don't care about their history.

### What's changed
Add test for model Hand Landmark, including a test image (in the context of a "hand", of course) and a model task object file.

### CODE REVIEW

**Comment by ayerofieiev-tt** [comment]
@cthsieh which file is not commited with LFS?

**Comment by cthsieh** [comment]
> @cthsieh which file is not commited with LFS?

Files involved in this PR.
```
hand_landmark
├── hand_landmarker.task            LFS file.
├── test_hand_landmark.py          Normal git file.
└── woman_hands.jpg                  LFS file.
```

**Review by ayerofieiev-tt — APPROVED** [review]

**Comment by cthsieh** [comment]
The CI failed due to the same reason as in #141, which needs `git lfs pull` to derive the LFS files.

https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/10860030910/job/30140837416

**Comment by ayerofieiev-tt** [comment]
I added git lfs pull to the workflow. Need to check why one model passed and another did not

**Comment by cthsieh** [comment]
Passed the CI. https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/10875361939

The trick is to make the test perform `git lfs pull` by itself.

**Pull request merged**
